import { DocumentData } from '@/types';

export const SAMPLE_DOCUMENTS: DocumentData[] = [
  // 1. AI in Structural Biology & Protein Folding
  {
    id: 'ai-structural-biology-protein-folding',
    title: 'Study Guide 1: AI in Structural Biology & Protein Folding',
    filename: '01_AI_in_Structural_Biology_and_Protein_Folding.md',
    fileSize: 2913,
    pageCount: 4,
    fileType: 'md',
    category: 'biology',
    isSample: true,
    createdAt: '2026-08-29T10:00:00.000Z',
    updatedAt: '2026-08-29T10:00:00.000Z',
    description: 'Computational biology study guide covering Levinthals Paradox, AlphaFold2/3, Evoformer, ESMFold, RFdiffusion, and de novo therapeutic protein design.',
    tags: ['Computational Biology', 'AlphaFold', 'Protein Folding', 'Deep Learning'],
    conceptGraph: {
      concepts: [
        {
          id: 'protein-folding-problem',
          name: 'The Protein Folding Problem & Levinthal\'s Paradox',
          definition: 'A 100-residue polypeptide has ~10^47 possible conformations. Random sampling would take longer than the age of the universe (>10^10 years), yet proteins fold spontaneously in milliseconds guided by free-energy funnel landscapes.',
          pageNumber: 1,
          sectionTitle: '1. The Protein Folding Problem',
          difficulty: 'beginner',
          prerequisites: [],
          dependents: ['alphafold-evoformer'],
          status: 'mastered',
          analogy: 'Like a ball rolling down an uneven funnel-shaped mountain: instead of wandering randomly over every square meter of earth, gravity pulls it directly toward the lowest energy basin.',
          visualDiagram: `1D Amino Acid Chain ---> [ Energy Funnel Landscape ] ---> Functional 3D Native Fold (Microseconds)`,
        },
        {
          id: 'alphafold-evoformer',
          name: 'AlphaFold & The Evoformer Architecture',
          definition: 'Deep learning neural architecture utilizing Multiple Sequence Alignments (MSAs) and pair representations with Invariant Point Attention (IPA) to predict atomic coordinates in 3D Euclidean space.',
          pageNumber: 2,
          sectionTitle: '2. Deep Learning: AlphaFold & ESMFold',
          difficulty: 'intermediate',
          prerequisites: ['protein-folding-problem'],
          dependents: ['esmfold-plm', 'generative-protein-design'],
          status: 'learning',
          analogy: 'Like having millions of historical blueprint variations (evolutionary MSA) and a 3D geometry engine iteratively aligning puzzle pieces with physical constraints.',
          visualDiagram: `MSA Sequences + Pair Features ---> [ Evoformer (48 Blocks) ] ---> [ Invariant Point Attention ] ---> 3D Coordinates`,
        },
        {
          id: 'esmfold-plm',
          name: 'ESMFold & Protein Language Models',
          definition: 'Meta AI large protein language model (ESM-2) trained across billions of evolutionary sequences. Predicts high-accuracy 3D structures directly from single sequences at orders-of-magnitude faster inference speeds than MSA pipelines.',
          pageNumber: 2,
          sectionTitle: '2. Deep Learning: AlphaFold & ESMFold',
          difficulty: 'intermediate',
          prerequisites: ['alphafold-evoformer'],
          dependents: ['generative-protein-design'],
          status: 'learning',
          analogy: 'Just as Large Language Models learn human grammar and semantics from text, ESMFold learns biophysical folding rules and evolutionary grammar directly from amino acid letters.',
          visualDiagram: `Single Sequence ---> [ ESM-2 (15B Parameters) ] ---> [ Structure Module ] ---> 3D Atomic Structure (Milliseconds)`,
        },
        {
          id: 'generative-protein-design',
          name: 'De Novo Design (RFdiffusion & ProteinMPNN)',
          definition: 'Generative diffusion probabilistic models that denoise random Gaussian coordinate noise into functional macromolecular backbones, creating novel binders, nanobodies, and catalytic active sites.',
          pageNumber: 3,
          sectionTitle: '3. De Novo Design & Therapeutic Applications',
          difficulty: 'advanced',
          prerequisites: ['alphafold-evoformer', 'esmfold-plm'],
          dependents: [],
          status: 'struggling',
          analogy: 'Like AI image generation (Midjourney/DALL-E), but generating 3D molecular scaffolds in Euclidean space that precisely fit a pathogen\'s target lock.',
          visualDiagram: `Random 3D Noise ---> [ RFdiffusion Denoising Steps ] ---> Target Binder Scaffolds ---> [ ProteinMPNN Sequence Design ]`,
        },
      ],
      edges: [
        { source: 'protein-folding-problem', target: 'alphafold-evoformer', label: 'solved by' },
        { source: 'alphafold-evoformer', target: 'esmfold-plm', label: 'accelerated by' },
        { source: 'alphafold-evoformer', target: 'generative-protein-design', label: 'enables' },
        { source: 'esmfold-plm', target: 'generative-protein-design', label: 'scores' },
      ],
    },
    sections: [
      { id: 'sec-1', title: '1. The Protein Folding Problem & Paradox', pageStart: 1, pageEnd: 1 },
      { id: 'sec-2', title: '2. Deep Learning: AlphaFold & ESMFold', pageStart: 2, pageEnd: 2 },
      { id: 'sec-3', title: '3. De Novo Design & Therapeutic Applications', pageStart: 3, pageEnd: 3 },
      { id: 'sec-4', title: '4. Self-Check Review & Key Takeaways', pageStart: 4, pageEnd: 4 },
    ],
    pages: [
      {
        pageNumber: 1,
        headings: ['1. Introduction and The Protein Folding Problem', 'Levinthal\'s Paradox'],
        conceptIds: ['protein-folding-problem'],
        tokenEstimate: 380,
        text: `# Study Guide 1: AI in Structural Biology and Protein Folding\n\n*Interdisciplinary Study Guide | Computational Biology and Artificial Intelligence*\n\n---\n\n## 1. Introduction and The Protein Folding Problem\n\n- **Proteins as Biological Machinery**: Fundamental workhorses performing enzymatic catalysis, structural integrity, signal transduction, and immune response.\n- **Primary to Tertiary Structure**: The 1D amino acid sequence dictates the functional 3D conformation (Anfinsen\'s Thermodynamic Hypothesis).\n- **Levinthal\'s Paradox**: A 100-residue polypeptide has ~10^47 potential conformations; random conformational search would take longer than the age of the universe (>10^10 years), yet biological proteins fold spontaneously in microseconds to milliseconds.\n- **Traditional Experimental Limits**: X-ray crystallography, Cryo-EM, and NMR spectroscopy are labor-intensive, taking months to years per structure at high capital expense.`,
      },
      {
        pageNumber: 2,
        headings: ['2. Deep Learning Breakthroughs: AlphaFold and ESMFold', 'Confidence Metrics (pLDDT & PAE)'],
        conceptIds: ['alphafold-evoformer', 'esmfold-plm'],
        tokenEstimate: 420,
        text: `## 2. Deep Learning Breakthroughs: AlphaFold and ESMFold\n\n- **AlphaFold2 and AlphaFold3 (Google DeepMind)**: Incorporates the Evoformer neural architecture, processing Multiple Sequence Alignments (MSAs) and pair representations with Invariant Point Attention (IPA) directly in 3D Euclidean space.\n- **AlphaFold3 Evolution**: Integrates diffusion-based generative modules capable of predicting complex assemblies including protein-DNA, protein-RNA, post-translational modifications, and small-molecule ligands.\n- **ESMFold (Meta AI)**: Utilizes large protein language models (ESM-2) trained across billions of evolutionary sequences. Predicts high-accuracy 3D structures directly from single sequences at orders-of-magnitude faster inference speeds than MSA-dependent pipelines.\n- **Confidence Metrics**: **pLDDT** (predicted Local Distance Difference Test, residue-level local confidence: >90 = high accuracy) and **PAE** (Predicted Aligned Error, assessing relative domain orientations).`,
      },
      {
        pageNumber: 3,
        headings: ['3. De Novo Design and Therapeutic Applications', 'Generative Diffusion in Protein Engineering'],
        conceptIds: ['generative-protein-design'],
        tokenEstimate: 390,
        text: `## 3. De Novo Design and Therapeutic Applications\n\n- **Generative Protein Design (RFdiffusion and ProteinMPNN)**: Designing completely novel, non-natural proteins, binders, nanobodies, and catalytic active sites from scratch.\n- **Target-Based Virtual Screening**: Rapidly mapping cryptic allosteric pockets and docking billions of small-molecule drug candidates in silico.\n- **Antibody Engineering**: Optimizing Complementarity Determining Region (CDR) loops to increase target affinity, stability, and reduce in vivo immunogenicity.`,
      },
      {
        pageNumber: 4,
        headings: ['4. Key Takeaways and Self-Check Review Questions', 'Summary & Synthesis'],
        conceptIds: ['protein-folding-problem', 'alphafold-evoformer', 'generative-protein-design'],
        tokenEstimate: 320,
        text: `## 4. Key Takeaways and Self-Check Review Questions\n\n- **Q1**: Explain how Levinthal\'s Paradox highlights the necessity of directed folding energy landscapes rather than random sampling.\n- **Q2**: What trade-off exists between ESMFold (single-sequence PLM) and AlphaFold2 (MSA-based Evoformer)?\n- **Q3**: How does RFdiffusion apply denoising diffusion probabilistic models to macromolecular backbone generation?\n\n> *Use the Study Assistant or "I\'m Lost" button anytime to break down these mechanisms step-by-step!*`,
      },
    ],
  },

  // 2. Biological vs Artificial Neural Networks
  {
    id: 'biological-vs-artificial-neural-networks',
    title: 'Study Guide 2: Biological Neurons vs. Artificial Neural Networks',
    filename: '02_Biological_vs_Artificial_Neural_Networks.md',
    fileSize: 2763,
    pageCount: 4,
    fileType: 'md',
    category: 'ai',
    isSample: true,
    createdAt: '2026-08-29T10:00:00.000Z',
    updatedAt: '2026-08-29T10:00:00.000Z',
    description: 'Neurobiology and AI study guide exploring action potentials, Hodgkin-Huxley, synaptic plasticity, backpropagation weight transport, SNNs, and neuromorphic chips (Intel Loihi 2).',
    tags: ['Neuroscience', 'Deep Learning', 'Neuromorphic', 'Spiking Neural Networks'],
    conceptGraph: {
      concepts: [
        {
          id: 'action-potentials-spikes',
          name: 'Action Potentials & Hodgkin-Huxley Dynamics',
          definition: 'All-or-nothing electrochemical membrane depolarizations governed by voltage-gated Na+ and K+ ion channels, enabling asynchronous discrete temporal communication in biological neurons.',
          pageNumber: 1,
          sectionTitle: '1. Biological Neurobiology Fundamentals',
          difficulty: 'beginner',
          prerequisites: [],
          dependents: ['hebbian-plasticity', 'weight-transport-problem'],
          status: 'mastered',
          analogy: 'Like a digital telegraph wire: the signal is not continuous voltage varying in size, but rather binary rhythmic pulses whose timing and frequency carry the message.',
          visualDiagram: `Dendrites ---> [ Soma Integration ] ---> [ Axon Hillock Threshold ] ---> Action Potential Spike (1-2 ms)`,
        },
        {
          id: 'hebbian-plasticity',
          name: 'Synaptic Plasticity & Hebbian Learning (STDP)',
          definition: '"Neurons that fire together, wire together." Long-Term Potentiation (LTP) and Long-Term Depression (LTD) dynamically scale synaptic efficacy based on local spike timing (Spike-Timing-Dependent Plasticity).',
          pageNumber: 1,
          sectionTitle: '1. Biological Neurobiology Fundamentals',
          difficulty: 'intermediate',
          prerequisites: ['action-potentials-spikes'],
          dependents: ['spiking-neural-networks'],
          status: 'mastered',
          analogy: 'Like a dirt trail in a forest: the more frequently people walk between two points in close succession, the wider and smoother the path becomes.',
          visualDiagram: `Pre-Neuron Spike --(Δt < 20ms)--> Post-Neuron Spike ===> Synaptic Weight W Strengthens (LTP)`,
        },
        {
          id: 'weight-transport-problem',
          name: 'The Weight Transport Problem in Backprop',
          definition: 'Standard artificial backpropagation requires exact transpose weight matrices (W^T) to propagate error gradients backwards—a symmetric wiring mechanism with no plausible biological equivalent in cortical neural tissue.',
          pageNumber: 2,
          sectionTitle: '2. ANNs: Abstractions & Biological Divergence',
          difficulty: 'intermediate',
          prerequisites: ['action-potentials-spikes'],
          dependents: ['spiking-neural-networks', 'neuromorphic-hardware'],
          status: 'learning',
          analogy: 'Imagine needing an exact mirror-image twin of every neuron in the brain whose sole job is to tell the forward neuron how its connection was weighted during an error signal.',
          visualDiagram: `Forward: y = W*x  <--->  Backward: dL/dx = W^T * dL/dy (Biological tissue has no W^T mirror mechanism)`,
        },
        {
          id: 'spiking-neural-networks',
          name: 'Spiking Neural Networks & Neuromorphic Hardware',
          definition: '3rd-generation neural networks communicating via discrete, sparse temporal spikes (LIF models). Executed on event-driven neuromorphic silicon (Intel Loihi 2, TrueNorth) achieving 10x-1000x energy efficiency over GPUs.',
          pageNumber: 3,
          sectionTitle: '3. Neuromorphic Computing & SNNs',
          difficulty: 'advanced',
          prerequisites: ['hebbian-plasticity', 'weight-transport-problem'],
          dependents: [],
          status: 'struggling',
          analogy: 'Standard GPUs are like a stadium where every seat is powered on full blast every second. Neuromorphic chips are like motion sensor lights: energy is consumed ONLY when a footstep arrives.',
          visualDiagram: `Asynchronous Spike Events ---> [ Leaky Integrate-and-Fire (LIF) ] ---> Sparse Event Output (~20W Whole Brain)`,
        },
      ],
      edges: [
        { source: 'action-potentials-spikes', target: 'hebbian-plasticity', label: 'regulates' },
        { source: 'action-potentials-spikes', target: 'weight-transport-problem', label: 'contrasts with' },
        { source: 'hebbian-plasticity', target: 'spiking-neural-networks', label: 'implemented in' },
        { source: 'weight-transport-problem', target: 'neuromorphic-hardware', label: 'resolved by' },
      ],
    },
    sections: [
      { id: 'sec-1', title: '1. Biological Neurobiology Fundamentals', pageStart: 1, pageEnd: 1 },
      { id: 'sec-2', title: '2. ANNs & Biological Divergence', pageStart: 2, pageEnd: 2 },
      { id: 'sec-3', title: '3. Neuromorphic Hardware & SNNs', pageStart: 3, pageEnd: 3 },
      { id: 'sec-4', title: '4. Self-Check Review Questions', pageStart: 4, pageEnd: 4 },
    ],
    pages: [
      {
        pageNumber: 1,
        headings: ['1. Biological Neurobiology Fundamentals', 'Synaptic Plasticity & LTP'],
        conceptIds: ['action-potentials-spikes', 'hebbian-plasticity'],
        tokenEstimate: 370,
        text: `# Study Guide 2: Biological Neurons vs. Artificial Neural Networks and Neuromorphic AI\n\n*Interdisciplinary Study Guide | Computational Biology and Artificial Intelligence*\n\n---\n\n## 1. Biological Neurobiology Fundamentals\n\n- **Neuron Architecture**: Dendrites receive electrochemical signals, the Soma integrates membrane potentials, the Axon Hillock initiates action potentials, and the Synapse releases neurotransmitters across the synaptic cleft.\n- **Action Potentials (Spikes)**: All-or-nothing threshold depolarizations governed by voltage-gated Na+ and K+ channels (described by the biophysical Hodgkin-Huxley differential equations).\n- **Synaptic Plasticity and Hebbian Learning**: *Neurons that fire together, wire together* -- the biochemical basis for Long-Term Potentiation (LTP), Long-Term Depression (LTD), and memory consolidation.`,
      },
      {
        pageNumber: 2,
        headings: ['2. Artificial Neural Networks (ANNs): Abstractions & Biological Divergence', 'Energy Efficiency & Weight Transport'],
        conceptIds: ['weight-transport-problem'],
        tokenEstimate: 390,
        text: `## 2. Artificial Neural Networks (ANNs): Abstractions and Biological Divergence\n\n- **Continuous Activations**: Modern deep learning uses continuous values passing through static nonlinear activation functions (ReLU, GELU, Swish) evaluated in synchronous matrix multiply batches.\n- **Backpropagation and Weight Transport Problem**: Backprop requires exact transpose weight matrices to propagate error gradients backwards -- a mechanism with no plausible biological equivalent in neural tissue.\n- **Energy Efficiency Disparity**: The adult human brain executes complex cognitive tasks on ~20 Watts of power across ~86 billion neurons and 100+ trillion synapses; training and running modern frontier LLMs requires megawatt-scale datacenter clusters.`,
      },
      {
        pageNumber: 3,
        headings: ['3. Neuromorphic Computing and Spiking Neural Networks (SNNs)', 'Event-Driven Silicon (Intel Loihi 2)'],
        conceptIds: ['spiking-neural-networks'],
        tokenEstimate: 360,
        text: `## 3. Neuromorphic Computing and Spiking Neural Networks (SNNs)\n\n- **Spiking Neural Networks (SNNs)**: 3rd-generation neural models communicating via discrete, asynchronous temporal spikes (utilizing Leaky Integrate-and-Fire / LIF neuron models).\n- **Neuromorphic Hardware (Intel Loihi 2, IBM TrueNorth, SpiNNaker)**: Event-driven architecture that draws power only when an active spike event arrives, yielding 10x-1000x energy reductions for temporal streaming data.\n- **Brain-Computer Interfaces (BCIs)**: Neural decoders translating real-time motor cortex multi-unit spike trains into robotic limb and communication cursor trajectories.`,
      },
      {
        pageNumber: 4,
        headings: ['4. Key Takeaways and Self-Check Review Questions', 'Summary & Synthesis'],
        conceptIds: ['action-potentials-spikes', 'weight-transport-problem', 'spiking-neural-networks'],
        tokenEstimate: 320,
        text: `## 4. Key Takeaways and Self-Check Review Questions\n\n- **Q1**: Why does the weight transport problem prevent standard backpropagation from serving as a direct model for cortical learning?\n- **Q2**: Distinguish between rate coding and temporal/spike-timing dependent plasticity (STDP) in biological and artificial neural networks.\n- **Q3**: What architectural factors allow neuromorphic chips to achieve orders of magnitude higher energy efficiency than traditional GPUs for event-based data?\n\n> *Use the Study Assistant or "I\'m Lost" button anytime to break down these mechanisms step-by-step!*`,
      },
    ],
  },

  // 3. Genomics, CRISPR & Bioinformatics ML
  {
    id: 'genomics-crispr-bioinformatics-ml',
    title: 'Study Guide 3: Genomics, CRISPR Gene Editing & Machine Learning',
    filename: '03_Genomics_CRISPR_and_Bioinformatics_ML.md',
    fileSize: 2556,
    pageCount: 4,
    fileType: 'md',
    category: 'genetics',
    isSample: true,
    createdAt: '2026-08-29T10:00:00.000Z',
    updatedAt: '2026-08-29T10:00:00.000Z',
    description: 'High-throughput sequencing and genomics guide covering DeepVariant CNN variant callers, CRISPR-Cas9 off-target prediction, HyenaDNA, Enformer, and genomic regulatory syntax.',
    tags: ['Genomics', 'CRISPR', 'Bioinformatics', 'Transformers', 'DeepVariant'],
    conceptGraph: {
      concepts: [
        {
          id: 'next-gen-sequencing',
          name: 'Next-Generation Sequencing & DeepVariant',
          definition: 'High-throughput short-read (Illumina) and long-read (PacBio, Oxford Nanopore) sequencing. Google DeepVariant translates aligned read pileups into multi-channel image tensors, using CNNs for superior variant calling.',
          pageNumber: 1,
          sectionTitle: '1. NGS & High-Throughput Genomics',
          difficulty: 'beginner',
          prerequisites: [],
          dependents: ['crispr-guide-optimization'],
          status: 'mastered',
          analogy: 'Instead of statistical spreadsheets, DeepVariant takes a "photograph" of aligned DNA reads and uses computer vision to spot genuine genetic mutations from sequencing errors.',
          visualDiagram: `Raw Reads ---> [ Reference Alignment (BWA-MEM) ] ---> [ Pileup Image Tensor ] ---> [ CNN Inception ] ---> Variants (SNPs/Indels)`,
        },
        {
          id: 'crispr-guide-optimization',
          name: 'CRISPR Guide RNA Optimization & Off-Target ML',
          definition: 'Predicting Cas9 cleavage efficacy and unintended off-target double-strand breaks. Deep neural networks (DeepCRISPR, Elevation) model chromatin accessibility and thermodynamic mismatch tolerance to design safe gRNAs.',
          pageNumber: 2,
          sectionTitle: '2. CRISPR-Cas9 & Guide RNA Optimization',
          difficulty: 'intermediate',
          prerequisites: ['next-gen-sequencing'],
          dependents: ['genomic-foundation-models'],
          status: 'learning',
          analogy: 'Like designing a laser-guided key: it must fit the target biological door perfectly with high energy while having zero tolerance to open any dangerous neighboring doors in the 3-billion letter genome.',
          visualDiagram: `gRNA Sequence + PAM + Epigenetic State ---> [ DeepCRISPR Network ] ---> On-Target Score & Off-Target Risk Map`,
        },
        {
          id: 'genomic-foundation-models',
          name: 'Genomic Foundation Models (HyenaDNA, Enformer)',
          definition: 'Sub-quadratic long-range state-space models and Transformers trained on hundreds of billions of base pairs across species, predicting cell-type gene expression and non-coding regulatory syntax up to 1Mb.',
          pageNumber: 3,
          sectionTitle: '3. Genomic Foundation Models & Syntax',
          difficulty: 'advanced',
          prerequisites: ['crispr-guide-optimization'],
          dependents: [],
          status: 'struggling',
          analogy: 'Reading DNA not as isolated words, but as an entire epic novel where a footnote on page 10 (an enhancer 100kb away) controls the character\'s fate on page 100 (promoter gene expression).',
          visualDiagram: `1Mb DNA Sequence ---> [ HyenaDNA / Enformer Long-Range Attention ] ---> Chromatin Openness & 5,313 Epigenomic Tracks`,
        },
      ],
      edges: [
        { source: 'next-gen-sequencing', target: 'crispr-guide-optimization', label: 'targets identified by' },
        { source: 'crispr-guide-optimization', target: 'genomic-foundation-models', label: 'contextualized by' },
      ],
    },
    sections: [
      { id: 'sec-1', title: '1. NGS & High-Throughput Genomics', pageStart: 1, pageEnd: 1 },
      { id: 'sec-2', title: '2. CRISPR-Cas9 & gRNA Optimization', pageStart: 2, pageEnd: 2 },
      { id: 'sec-3', title: '3. Genomic Foundation Models & Syntax', pageStart: 3, pageEnd: 3 },
      { id: 'sec-4', title: '4. Self-Check Review Questions', pageStart: 4, pageEnd: 4 },
    ],
    pages: [
      {
        pageNumber: 1,
        headings: ['1. Next-Generation Sequencing (NGS) and High-Throughput Genomics', 'DeepVariant CNN Variant Calling'],
        conceptIds: ['next-gen-sequencing'],
        tokenEstimate: 360,
        text: `# Study Guide 3: Genomics, CRISPR Gene Editing and Machine Learning\n\n*Interdisciplinary Study Guide | Computational Biology and Artificial Intelligence*\n\n---\n\n## 1. Next-Generation Sequencing (NGS) and High-Throughput Genomics\n\n- **Sequencing Paradigms**: Short-read sequencing (Illumina: high accuracy, short read lengths) vs. Long-read single-molecule sequencing (PacBio HiFi, Oxford Nanopore: resolving complex structural variations and repetitive regions).\n- **Bioinformatic Pipelines**: Basecalling, quality filtering, reference alignment (BWA-MEM, Minimap2), and variant discovery (SNPs, Indels, Copy Number Variations).\n- **DeepVariant (Google Health)**: Translates aligned sequencing read pileups into multi-channel image tensors, using Convolutional Neural Networks (CNNs) to surpass traditional statistical variant callers in accuracy.`,
      },
      {
        pageNumber: 2,
        headings: ['2. CRISPR-Cas9 Precision and Guide RNA Optimization', 'Off-Target Cleavage & Machine Learning'],
        conceptIds: ['crispr-guide-optimization'],
        tokenEstimate: 380,
        text: `## 2. CRISPR-Cas9 Precision and Guide RNA Optimization\n\n- **CRISPR Mechanism**: An RNA-guided Cas9 endonuclease recognizes a specific Protospacer Adjacent Motif (PAM) sequence and introduces targeted double-strand breaks for precise genome editing.\n- **Off-Target Cleavage**: Cas9 endonuclease can tolerate partial base mismatches between guide RNA (gRNA) and non-target genomic loci, causing dangerous unintended genomic mutations.\n- **Machine Learning Predictors (CRISPRon, DeepCRISPR, Elevation)**: Deep neural networks trained on epigenetic features, chromatin openness, and sequence thermodynamics to optimize gRNA on-target cutting efficiency and suppress off-target cleavage risk.`,
      },
      {
        pageNumber: 3,
        headings: ['3. Genomic Foundation Models and Regulatory Syntax', 'Predicting Non-Coding Variant Effects'],
        conceptIds: ['genomic-foundation-models'],
        tokenEstimate: 390,
        text: `## 3. Genomic Foundation Models and Regulatory Syntax\n\n- **Genomic Language Models (HyenaDNA, Nucleotide Transformer, DNABERT)**: Transformer and sub-quadratic state-space architectures trained on hundreds of billions of nucleotides across diverse species.\n- **Predicting Non-Coding Variant Effects (Enformer, Borzoi)**: Utilizing deep learning architectures with long-range receptive fields (up to 100kb-1Mb) to predict cell-type-specific gene expression, enhancer-promoter contacts, and histone modifications directly from DNA sequence.`,
      },
      {
        pageNumber: 4,
        headings: ['4. Key Takeaways and Self-Check Review Questions', 'Summary & Synthesis'],
        conceptIds: ['next-gen-sequencing', 'crispr-guide-optimization', 'genomic-foundation-models'],
        tokenEstimate: 310,
        text: `## 4. Key Takeaways and Self-Check Review Questions\n\n- **Q1**: How does DeepVariant frame biological variant calling as a computer vision classification task?\n- **Q2**: Why is chromatin accessibility (e.g., ATAC-seq data) critical for predicting CRISPR guide RNA efficacy in living cells?\n- **Q3**: What advantages do long-context architectures like HyenaDNA offer over standard quadratic attention when analyzing eukaryotic regulatory regions?\n\n> *Use the Study Assistant or "I\'m Lost" button anytime to break down these mechanisms step-by-step!*`,
      },
    ],
  },

  // 4. Synthetic Biology & Evolutionary Computing
  {
    id: 'synthetic-biology-evolutionary-computing',
    title: 'Study Guide 4: Synthetic Biology & Evolutionary Computing',
    filename: '04_Synthetic_Biology_and_Evolutionary_Algorithms.md',
    fileSize: 2305,
    pageCount: 4,
    fileType: 'md',
    category: 'biology',
    isSample: true,
    createdAt: '2026-08-29T10:00:00.000Z',
    updatedAt: '2026-08-29T10:00:00.000Z',
    description: 'Engineering biology study guide exploring the DBTL cycle, genetic algorithms, in silico directed evolution, Bayesian active learning, cloud biofoundries, and biosecurity.',
    tags: ['Synthetic Biology', 'Evolutionary Algorithms', 'Biofoundry', 'Genetic Algorithms'],
    conceptGraph: {
      concepts: [
        {
          id: 'dbtl-framework',
          name: 'The DBTL Engineering Cycle & BioBricks',
          definition: 'The iterative Design-Build-Test-Learn cycle applying engineering principles to biology, assembling standardized genetic parts (promoters, RBS, terminators) to program synthetic metabolic pathways.',
          pageNumber: 1,
          sectionTitle: '1. Principles of Synthetic Biology',
          difficulty: 'beginner',
          prerequisites: [],
          dependents: ['in-silico-directed-evolution'],
          status: 'mastered',
          analogy: 'Treating biology like electrical engineering: BioBricks are standard transistors and resistors, and the DBTL cycle is the iterative prototyping of a circuit board.',
          visualDiagram: `[ DESIGN ] ---> [ BUILD (DNA Assembly) ] ---> [ TEST (Assays/Spectrometry) ] ---> [ LEARN (ML Optimization) ]`,
        },
        {
          id: 'in-silico-directed-evolution',
          name: 'In Silico Directed Evolution & Genetic Algorithms',
          definition: 'Evolutionary optimization algorithms combining fitness surrogate models (GNNs, random forests) and Bayesian active learning to navigate immense combinatorial sequence spaces before wet-lab synthesis.',
          pageNumber: 2,
          sectionTitle: '2. Evolutionary Algorithms & Bio-Inspired AI',
          difficulty: 'intermediate',
          prerequisites: ['dbtl-framework'],
          dependents: ['autonomous-cloud-biofoundries'],
          status: 'learning',
          analogy: 'Instead of screening 1,000,000 test tubes randomly, an AI surrogate tests billions in simulation and tells the robot the top 100 most informative candidates to synthesize.',
          visualDiagram: `Sequence Population ---> [ Fitness Surrogate Model ] ---> [ Selection & Crossover ] ---> Top 0.01% High-Yield Variants`,
        },
        {
          id: 'autonomous-cloud-biofoundries',
          name: 'Autonomous Cloud Biofoundries & Biosecurity',
          definition: 'Closed-loop self-driving wet laboratories integrating automated liquid handlers and RL agents with neural DNA order screening to defend against pathogen synthesis risks.',
          pageNumber: 3,
          sectionTitle: '3. Cloud Biofoundries & Biosecurity',
          difficulty: 'advanced',
          prerequisites: ['in-silico-directed-evolution'],
          dependents: [],
          status: 'struggling',
          analogy: 'An automated semiconductor fab, but for living cells: robots run experiments 24/7, while AI security scanners verify every sequence before synthesis.',
          visualDiagram: `RL Bayesian Optimizer <---> [ Liquid Handling Robotics ] ---> Automated Plate Readers ---> [ DNA Synthesis Guardrails ]`,
        },
      ],
      edges: [
        { source: 'dbtl-framework', target: 'in-silico-directed-evolution', label: 'accelerates Learn phase' },
        { source: 'in-silico-directed-evolution', target: 'autonomous-cloud-biofoundries', label: 'orchestrates' },
      ],
    },
    sections: [
      { id: 'sec-1', title: '1. Principles of Synthetic Biology', pageStart: 1, pageEnd: 1 },
      { id: 'sec-2', title: '2. Evolutionary Algorithms & Bio-AI', pageStart: 2, pageEnd: 2 },
      { id: 'sec-3', title: '3. Cloud Biofoundries & Biosecurity', pageStart: 3, pageEnd: 3 },
      { id: 'sec-4', title: '4. Self-Check Review Questions', pageStart: 4, pageEnd: 4 },
    ],
    pages: [
      {
        pageNumber: 1,
        headings: ['1. Principles of Synthetic Biology and Engineering Biology', 'The DBTL Framework & BioBricks'],
        conceptIds: ['dbtl-framework'],
        tokenEstimate: 360,
        text: `# Study Guide 4: Synthetic Biology and Evolutionary Computing\n\n*Interdisciplinary Study Guide | Computational Biology and Artificial Intelligence*\n\n---\n\n## 1. Principles of Synthetic Biology and Engineering Biology\n\n- **The DBTL Framework**: The iterative Design-Build-Test-Learn engineering cycle driving rational bio-design and cell programming.\n- **Standardized Modular Parts (BioBricks)**: Characterized promoters, Ribosome Binding Sites (RBS), open reading frames, and terminators assembled into predictable synthetic genetic circuits.\n- **Metabolic Engineering**: Rewiring endogenous cellular biochemical pathways in microbial hosts (yeast, E. coli) to synthesize pharmaceuticals (e.g., artemisinin), bio-monomers, and green fuels.`,
      },
      {
        pageNumber: 2,
        headings: ['2. Evolutionary Algorithms and Bio-Inspired AI', 'In Silico Directed Evolution & Bayesian Optimization'],
        conceptIds: ['in-silico-directed-evolution'],
        tokenEstimate: 380,
        text: `## 2. Evolutionary Algorithms and Bio-Inspired AI\n\n- **Genetic Algorithms (GAs) and Genetic Programming**: Metaheuristic optimization mimicking natural selection -- maintaining candidate solution populations undergoing fitness evaluation, tournament selection, crossover (recombination), and stochastic mutation.\n- **In Silico Directed Evolution**: Running hundreds of computational evolution iterations using surrogate fitness models (GNNs, random forests) before expensive wet-lab library synthesis.\n- **Active Learning and Bayesian Optimization**: Intelligently selecting the most informative experimental variants to test in high-dimensional combinatorial biological search spaces.`,
      },
      {
        pageNumber: 3,
        headings: ['3. Autonomous Cloud Biofoundries and Biosecurity', 'Self-Driving Laboratories & DNA Screening'],
        conceptIds: ['autonomous-cloud-biofoundries'],
        tokenEstimate: 370,
        text: `## 3. Autonomous Cloud Biofoundries and Biosecurity\n\n- **Self-Driving Laboratories**: Closed-loop automation combining automated liquid handlers, plate readers, and RL-guided Bayesian optimizers executing multi-day bioengineering experiments autonomously.\n- **Biosecurity and DNA Order Screening**: Neural classifiers and sequence-homology tools screening commercial gene synthesis orders against dangerous pathogens and toxin databases.`,
      },
      {
        pageNumber: 4,
        headings: ['4. Key Takeaways and Self-Check Review Questions', 'Summary & Synthesis'],
        conceptIds: ['dbtl-framework', 'in-silico-directed-evolution', 'autonomous-cloud-biofoundries'],
        tokenEstimate: 310,
        text: `## 4. Key Takeaways and Self-Check Review Questions\n\n- **Q1**: Describe the four phases of the DBTL cycle and how machine learning accelerates the Learn-to-Design transition.\n- **Q2**: How do surrogate machine learning models reduce the screening burden in directed enzyme evolution?\n- **Q3**: What biosecurity challenges emerge as automated DNA synthesis and AI-driven protein design capabilities scale?\n\n> *Use the Study Assistant or "I\'m Lost" button anytime to break down these mechanisms step-by-step!*`,
      },
    ],
  },
];
